@echo off 
echo 修复Shadowsocks的500/502/504错误，
echo.
echo (1)修改系统配置...
echo ...
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy" /v Enabled /t REG_DWORD /d 0 /f
netsh interface ipv4 reset
netsh interface ipv6 reset
netsh winsock reset
echo ...
echo 系统配置修复完毕！
echo ...
echo (2)关闭Shadowsocks客户端...
taskkill /f /im Shadowsocks* >nul 2>nul
echo ...
echo 修复完毕！请重启Shadowsocks客户端 
echo.
pause